parameters:
    xidea_product.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_product.template_configuration.default.class: Xidea\Bundle\BaseBundle\TemplateConfiguration
  
services:
    xidea_product.configuration.default:
        class: %xidea_product.configuration.default.class%
        arguments:
            - @xidea_product.template_configuration
    xidea_product.template_configuration.default:
        class: %xidea_product.template_configuration.default.class%
        arguments:
            - %xidea_product.template.namespace%
            - %xidea_product.template.templates%
            - %xidea_product.template.engine%