parameters:
    xidea_product.controller.list.class: Xidea\Bundle\ProductBundle\Controller\Product\ListController
    xidea_product.controller.show.class: Xidea\Bundle\ProductBundle\Controller\Product\ShowController
    xidea_product.controller.create.class: Xidea\Bundle\ProductBundle\Controller\Product\CreateController
  
services:
    xidea_product.controller.list:
        class: %xidea_product.controller.list.class%
        arguments:
            - @xidea_product.product.configuration
            - @xidea_product.product.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]
    xidea_product.controller.show:
        class: %xidea_product.controller.show.class%
        arguments:
            - @xidea_product.product.configuration
            - @xidea_product.product.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]
    xidea_product.controller.create:
        class: %xidea_product.controller.create.class%
        arguments:
            - @xidea_product.product.configuration
            - @xidea_product.product.director
            - @xidea_product.product.manager
            - @xidea_product.product.form.create.handler
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setRouter, [@router]]
            - [setTemplating, [@templating]]