parameters:
    xidea_product.controller.create.class: Xidea\Bundle\ProductBundle\Controller\Product\CreateController
  
services:
    xidea_product.controller.create:
        class: %xidea_product.controller.create.class%
        arguments:
            - @xidea_product.product_director
            - @xidea_product.product_manager
            - @xidea_product.product_create.form.handler
            - @event_dispatcher
            - @router
            - @templating