parameters:
    xidea_product.manufacturer.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_product.manufacturer.factory.default.class: Xidea\Component\Base\Factory\ModelFactory
  
services:
    xidea_product.manufacturer.configuration.default:
        class: %xidea_product.manufacturer.configuration.default.class%
        arguments:
            - @xidea_product.template.configuration
    xidea_product.manufacturer.factory.default:
        class: %xidea_product.manufacturer.factory.default.class%
        arguments:
            - %xidea_product.manufacturer.class%