parameters:
    xidea_product.product.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_product.product.factory.default.class: Xidea\Component\Base\Factory\ObjectFactory
    xidea_product.product.builder.default.class: Xidea\Component\Product\Builder\ProductBuilder
    xidea_product.product.director.default.class: Xidea\Component\Product\Builder\ProductDirector
    xidea_product.product.template.configuration.default.class: Xidea\Bundle\BaseBundle\TemplateConfiguration
  
services:
    xidea_product.product.configuration.default:
        class: %xidea_product.product.configuration.default.class%
        arguments:
            - @xidea_product.product.template.configuration
    xidea_product.product.template.configuration.default:
        class: %xidea_product.product.template.configuration.default.class%
        arguments:
            - %xidea_product.product.template.namespace%
            - %xidea_product.product.template.templates%
            - %xidea_product.product.template.engine%
    xidea_product.product.factory.default:
        class: %xidea_product.product.factory.default.class%
        arguments:
            - %xidea_product.product.class%
    xidea_product.product.builder.default:
        class: %xidea_product.product.builder.default.class%
        arguments:
            - @xidea_product.product.factory
    xidea_product.product.director.default:
        class: %xidea_product.product.director.default.class%
        arguments:
            - @xidea_product.product.builder