parameters:
    xidea_product.product.form.type.class: Xidea\Bundle\ProductBundle\Form\Type\ProductType
    xidea_product.product.form.create.factory.default.class: Xidea\Bundle\BaseBundle\Form\Factory\FormFactory
    xidea_product.product.form.create.handler.default.class: Xidea\Bundle\ProductBundle\Form\Handler\ProductFormHandler

services:
    xidea_product.product.form.type:
        class: %xidea_product.product.form.type.class%
        arguments:
            - %xidea_product.product.class%
        tags:
            - { name: form.type, alias: "xidea_product" }
    xidea_product.product.form.create.factory.default:
        class: %xidea_product.product.form.create.factory.default.class%
        arguments:
            - @form.factory
            - %xidea_product.product.form.create.name%
            - %xidea_product.product.form.create.type%
            - %xidea_product.product.form.create.validation_groups%
    xidea_product.product.form.create.handler.default:
        class: %xidea_product.product.form.create.handler.default.class%
        arguments:
            - @xidea_product.product.form.create.factory
            - @event_dispatcher