parameters:
    xidea_product.product_factory.class: Xidea\Component\Product\Factory\ProductFactory
    xidea_product.product_builder.class: Xidea\Component\Product\Builder\ProductBuilder
    xidea_product.product_director.class: Xidea\Component\Product\Builder\ProductDirector
  
services:
    xidea_product.product_factory.default:
        class: %xidea_product.product_factory.class%
        arguments:
            - %xidea_product.product.class%
    xidea_product.product_builder.default:
        class: %xidea_product.product_builder.class%
        arguments:
            - @xidea_product.product_factory
    xidea_product.product_director.default:
        class: %xidea_product.product_director.class%
        arguments:
            - @xidea_product.product_builder
            - @xidea_product.user_provider