parameters:
    xidea_product.user.provider.default.class: Xidea\Bundle\ProductBundle\Provider\UserProvider
  
services:
    xidea_product.user.provider.default:
        class: %xidea_product.user.provider.default.class%
        arguments:
            - @security.context