Xidea\Component\Product\Model\AbstractProduct:
    type: mappedSuperclass
    repositoryClass: Xidea\Bundle\ProductBundle\Doctrine\ORM\Repository\ProductRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        sku:
            type: string
            length: 128
        name:
            type: string
            length: 255
        description:
            type: text
        createdAt:
            column: created_at
            type: datetime
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
    manyToOne:
        manufacturer:
            targetEntity: Xidea\Component\Product\Model\ManufacturerInterface
            joinColumn:
                name: manufacturer_id
                referencedColumnName: id
        author:
            targetEntity: Xidea\Component\Product\Model\AuthorInterface
            joinColumn:
                name: author_id
                referencedColumnName: id
                nullable: false
#    lifecycleCallbacks:
#        prePersist: [ prePersist ]
#        preUpdate: [ preUpdate ]