Xidea\Component\Product\Model\AbstractProduct:
    type: mappedSuperclass
    repositoryClass: Xidea\Bundle\ProductBundle\Doctrine\ORM\Repository\ProductRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        sku:
            type: string
            length: 128
        slug:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        shortDescription:
            type: string
            length: 1024
            nullable: true
        url:
            type: string
            length: 512
            nullable: true
        price:
            type: decimal
            precision: 10
            scale: 2
            nullable: true
        retailPrice:
            type: decimal
            precision: 10
            scale: 2
            nullable: true
        qty:
            type: integer
            nullable: true
        image:
            type: string
            length: 512
            nullable: true
        imageLabel:
            type: string
            length: 255
            nullable: true
        width:
            type: decimal
            precision: 5
            scale: 2
            nullable: true
        height:
            type: decimal
            precision: 5
            scale: 2
            nullable: true
        depth:
            type: decimal
            precision: 5
            scale: 2
            nullable: true
        availableOn:
            column: available_on
            type: datetime
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
    manyToOne:
        manufacturer:
            targetEntity: Xidea\Component\Product\Model\ManufacturerInterface
            joinColumn:
                name: manufacturer_id
                referencedColumnName: id