Xidea\Component\Product\Model\AbstractProduct:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        id:
            expose: true
            type: integer
        name:
            expose: true
            type: string
        description:
            expose: true
            type: string
        createdAt:
            expose: true
            type: DateTime
        updatedAt:
            expose: true
            type: DateTime