xidea_product_list:
    pattern:  /products
    defaults: { _controller: xidea_product.product.controller.list:listAction }
 
xidea_product_show:
    pattern:  /products/{id}
    defaults: { _controller: xidea_product.product.controller.show:showAction }
    requirements:
        id:  \d+
    
xidea_product_create:
    pattern:  /products/create
    defaults: { _controller: xidea_product.product.controller.create:createAction }